"""Generate the Luau proof library and Rojo mappings from the exported Blender samples."""
import json
from pathlib import Path
ROOT = Path(__file__).resolve().parents[2]
def luau(value):
    if isinstance(value, dict):
        return '{' + ','.join('[' + json.dumps(k) + ']=' + luau(v) for k,v in value.items()) + '}'
    if isinstance(value, list): return '{' + ','.join(luau(v) for v in value) + '}'
    if isinstance(value, bool): return 'true' if value else 'false'
    if value is None: return 'nil'
    return json.dumps(value)
data = json.loads((ROOT/'assets/characters/pigeon/v1/proof-clips.json').read_text())
(ROOT/'game/src/ReplicatedStorage/Shared/BirdProofClips.luau').write_text('-- Generated by tools/characters/generate_runtime.py; rotational authoring bridge.\nreturn '+luau(data)+'\n')
project = ROOT/'game/default.project.json'
document = json.loads(project.read_text())
for name in ('BirdAnimationConfig','BirdAnimationState','BirdProofClips','BirdAnimationSequenceBuilder'):
    document['tree']['ReplicatedStorage']['Shared'][name] = {'$path':f'src/ReplicatedStorage/Shared/{name}.luau'}
document['tree']['ServerScriptService']['Services']['BirdVisualService'] = {'$path':'src/ServerScriptService/Services/BirdVisualService.luau'}
document['tree']['StarterPlayer']['StarterPlayerScripts']['Controllers']['BirdAnimationController'] = {'$path':'src/StarterPlayer/StarterPlayerScripts/Controllers/BirdAnimationController.luau'}
project.write_text(json.dumps(document,indent=2)+'\n')
print('Generated shared library and five Rojo mappings')
