// Runtime tables are generated from the reviewed content libraries; no asset IDs are invented.
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..');
const luau=v=>v===null?'nil':Array.isArray(v)?`{${v.map(luau).join(',')}}`:typeof v==='object'?`{${Object.entries(v).map(([k,x])=>`[${JSON.stringify(k)}]=${luau(x)}`).join(',')}}`:JSON.stringify(v);
const audio=JSON.parse(fs.readFileSync(path.join(root,'assets/audio/library.json')));
const vfx=JSON.parse(fs.readFileSync(path.join(root,'assets/vfx/library.json')));
const output={Audio:Object.fromEntries(audio.cues.map(c=>[c.id,{Name:c.name,SoundId:c.robloxId?`rbxassetid://${c.robloxId}`:'',Bus:c.bus,Looped:c.loop,Volume:c.category==='environment'?0.15:0.35,Lifetime:c.loop?0:8,Range:70}])),VFX:Object.fromEntries(vfx.effects.map(e=>[e.id,{Name:e.name,Lifetime:e.lifetimeSeconds,MaxActive:e.maxActive,MaxEmit:e.maxEmitPerBurst,Range:e.maxDistanceStuds}]))};
const destination='game/src/ReplicatedStorage/Shared/ContentDefinitions.luau';
fs.writeFileSync(path.join(root,destination),'-- Generated by tools/production/generate-content.mjs; edit asset libraries instead.\nreturn '+luau(output)+'\n');
const p=path.join(root,'game/default.project.json'),project=JSON.parse(fs.readFileSync(p));
project.tree.ReplicatedStorage.Shared.ContentDefinitions={$path:'src/ReplicatedStorage/Shared/ContentDefinitions.luau'};
for(const name of ['AudioController','VFXController'])project.tree.StarterPlayer.StarterPlayerScripts.Controllers[name]={$path:`src/StarterPlayer/StarterPlayerScripts/Controllers/${name}.luau`};
fs.writeFileSync(p,JSON.stringify(project,null,2)+'\n');
console.log('Generated 24 audio and 12 VFX runtime definitions and Rojo mappings');
