// Seed explicit production metadata. Run only when creating the library, not to overwrite approvals.
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const write=(name,data)=>{const p=path.join(root,name);fs.mkdirSync(path.dirname(p),{recursive:true});if(fs.existsSync(p))throw new Error(`Refusing to overwrite ${name}`);fs.writeFileSync(p,JSON.stringify(data,null,2)+'\n');};
const categories={bird:['WingFlap','Call','TakeOff','Land'],flight:['Wind','FastWind','DiveWind'],poop:['Release','Projectile','Splat','Headshot','Combo','Reward'],environment:['Traffic','CityAmbience','People','Dogs','Nature'],gameplay:['WantedIncrease','Capture','EggHatch','LegendaryHatch','PvPVictory','UIFeedback']};
const audio=[];
for(const [category,cues]of Object.entries(categories))for(const cue of cues){const loop=cue.includes('Wind')||['Traffic','CityAmbience','People','Nature'].includes(cue);audio.push({id:`${category}.${cue}`,name:`PB_${category[0].toUpperCase()+category.slice(1)}_${cue}_v01`,category,cue,status:'planned',robloxId:null,rights:'unreviewed',source:null,bus:category==='environment'?'PB_Ambience':cue==='UIFeedback'?'PB_UI':'PB_SFX',loop,hook:category==='bird'?'bird animation state/marker':category==='flight'?'flight state':category==='poop'?'ImpactService or validated Hit feedback':category==='environment'?'district ambience / NPC state':'accepted gameplay feedback; future hooks gated'});}
write('assets/audio/library.json',{schema:1,voiceBudgets:{oneShotsPerClient:48,flightLoopsPerBird:2,ambiencePerClient:4},master:{format:'WAV_PCM',sampleRate:48000,bits:16,peakDbfs:-3},cues:audio});
const vfxNames=['PoopSplat','Headshot','ScorePopup','Speed','Dive','Wanted','EggHatch','LegendaryReward','PvP','BirdAbility','Trail','Cosmetic'];
write('assets/vfx/library.json',{schema:1,effects:vfxNames.map(name=>({id:name,name:`PB_VFX_${name}_v01`,status:['PoopSplat','Headshot','ScorePopup'].includes(name)?'implemented':'planned',owner:name==='PoopSplat'?'server':'client presentation',hook:name==='PoopSplat'?'ImpactService.Splat':['Headshot','ScorePopup'].includes(name)?'UIController.animateHit':'future backend/state hook',lifetimeSeconds:name==='PoopSplat'?7:1.2,maxActive:name==='PoopSplat'?80:12,maxEmitPerBurst:name==='PoopSplat'?0:24,maxDistanceStuds:150,awardsGameplay:false}))});
const groups={environment:['Buildings','Trees','Rocks'],props:['Food','Trash','Benches','StreetProps','Signs','AnimalControlEquipment','Nests','Incubators','Shops','PvPArenaProps'],npcs:['Dogs','Citizens','AnimalControl'],ui:['HUD','BirdCollection','Nest','Eggs','Incubator','Breeding','Upgrades','Shop','Challenges','PvP','DailyRewards','Settings']};
const items=[];
for(const [category,names]of Object.entries(groups))for(const name of names){const isUI=category==='ui';const implemented=isUI&&['HUD','BirdCollection','Upgrades','Shop','DailyRewards'].includes(name);items.push({id:`${category}.${name}`,category,version:1,status:implemented?'implemented':['Rocks','Trash'].includes(name)?'planned':'blockout',source:isUI?'game/src/StarterPlayer/StarterPlayerScripts/Controllers/UIController.luau':category==='npcs'?'game/src/ServerScriptService/GameServer.server.luau':'game/src/ServerScriptService/Services/WorldBuilder.luau',files:[],rights:'project-authored',integration:isUI?'PlayerGui.PoopingBirdsUI':category==='npcs'?'Workspace.BirdCity runtime populations':'Workspace.BirdCity City/Hub',evidence:[],requiredForRelease:implemented});}
items.push({id:'characters.Pigeon',category:'characters',version:1,status:'proof',source:'assets/characters/meshy-character/profile.json',files:['assets/characters/pigeon/v1/Pigeon_Production.blend','assets/characters/pigeon/v1/Pigeon_Rig.fbx','assets/characters/pigeon/v1/Pigeon_Animated.glb','assets/characters/pigeon/v1/Pigeon_BaseColor.png'],rights:'user-supplied; commercial rights review pending',integration:'ServerStorage.BirdCharacterTemplates.Pigeon',roblox:{mesh:98474860366246,texture:91852723190945,animations:{}},evidence:['assets/characters/pigeon/v1/validation.json','assets/characters/pigeon/v1/export-roundtrip.json'],requiredForRelease:true});
write('assets/catalog.json',{schema:1,placeId:119022971112182,categories:['characters','environment','props','npcs','ui','audio','vfx'],assets:items});
write('assets/release-gates.json',{schema:1,gates:['studioSceneSaved','characterArtistReview','publishedAnimations','characterGameplayAndRespawn','audioRightsAndPlayback','multiplayer','privatePersistenceRoundtrip','physicalDevices','performance','restoreDrill','githubBackup'].map(id=>({id,status:'pending',evidence:null,reviewedAt:null}))});
console.log(`Created ${items.length} content records, ${audio.length} audio cues and ${vfxNames.length} VFX recipes.`);
